#cloud-config
package_upgrade: true
packages:
  - nginx
  - python3-pip
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          server_name _;

          location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
runcmd:
  - service nginx restart
  - cd /var/www/html
  - git clone https://github.com/llanos1205/CloudAssignment1Diego.git  # Clone your Django application repository
  - cd CloudAssignment1Diego # Navigate to your Django application directory
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt  # Install required Python packages
  - python3 manage.py collectstatic --noinput  # Collect static files
  - nohup python3 manage.py runserver 0.0.0.0:8000 &  # Start Django development server in the background
