#cloud-config
package_upgrade: true
packages:
  - nginx
runcmd:
  - cd /var/www/html
  - cd CloudAssignment1Diego # Navigate to your Django application directory
  - source venv/bin/activate
  - nohup sudo python3 manage.py runserver 0.0.0.0:8000 &
